### ISSUE TITLE
Question about dependencies

### ISSUE THREAD

**Issue by onwardmk** [shrimple-tech/action_policy-graphiti#1]
Does this gem assume that `graphiti-rails` is installed, or can I use it with only the `graphiti` gem?

> This gem is under heavy development so use it at your own risk!

I see this in the README, but there hasn't been any commits in 7 months. Is this statement still true, or is the gem pretty stable now?

**Comment by factyy** [comment]
@onwardmk , our initial intention was not to depend on `graphiti-rails`. However most of real-world use cases included `graphiti-rails` since we used this gem in Rails + Graphiti apps. I propose you give it a try and report any issues here.

As for the development phase we planned a few features (mostly integration with Graphiti resource field authorization and seamless relationship updates) that required quite a few modifications to Graphiti itself. Sadly we still haven't got time for this but the original plans are still there :)
